theme = "tokyonight"
 
[editor]
line-number = "relative"
true-color = true
cursorline = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "file-name", "spinner"]
right = ["diagnostics", "separator", "position", "separator", "file-type"]
separator = "~"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.lsp]
display-messages = true